apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: osrm
  template:
    metadata:
      labels:
        app: osrm
    spec:
      containers:
      - name: osrm-container
        image: your-username/osrm-aws-k8s-docker:latest
        ports:
        - containerPort: 5000
        # Add other configuration options as needed

