apiVersion: v1
kind: Service
metadata:
  name: osrm-service
spec:
  selector:
    app: osrm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Change to NodePort or ClusterIP based on your requirements

